bboard/bboard/urls.py
#Код модуля пакета конфигурации

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

bboard/main/urls.py
# Код модуля пакета приложения

from django.urls import path
from .views import index
from .views import other_page
from .views import BBLoginView
from .views import profile
from .views import BBLogoutView
from .views import ChangeUserInfoView
from .views import BBPasswordChangeView
from .views import RegisterUserView, RegisterDoneView
from .views import user_activate
from .views import DeleteUserView
app_name = 'main'

urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login', BBLoginView.as_view(), name='login'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index')
]

bboard/main/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.contrib.auth.models import AbstractUser

from django.dispatch import Signal
from django.utils.crypto import get_random_string

user_registrated = Signal('instance')


def get_name_file(instance, filename):
    return '/'.join([get_random_string(length=5) + '_' + filename])


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
                                       verbose_name='Прошел активацию?')
    middle_name = models.CharField(max_length=50, blank=True, null=True, default='', verbose_name='Отчество')
    apply_personal_data = models.BooleanField(default=False,
                                              verbose_name='Согласие на обработку персональных данных')

    class Meta(AbstractUser.Meta):
        pass

bboard/main/forms.py
from django import forms

from .models import AdvUser

from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import user_registrated


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'middle_name', 'apply_personal_data')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты', help_text='Валидный формат email - адрес')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Повторите тот же самый пароль еще раз')
    middle_name = forms.CharField(label='Отчество', help_text='Только кириллические буквы, дефис и пробелы')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        user.is_activated = True
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'middle_name', 'apply_personal_data')
        help_texts = {
            'username': 'Только латиница и дефис, уникальный',
            'first_name': 'Только кириллические буквы, дефис и пробелы',
            'last_name': 'Только кириллические буквы, дефис и пробелы',
        }

bboard/main/views.py
# Код контроллер-функции и код контроллер-класса

from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy

from .forms import ChangeUserInfoForm
from .models import AdvUser
from django.contrib.auth.views import PasswordChangeView

from .forms import RegisterUserForm

from django.views.generic.base import TemplateView

from django.core.signing import BadSignature
from .utilities import signer

from django.views.generic import UpdateView, CreateView, DeleteView
from django.contrib.auth import logout
from django.contrib import messages


def index(request):
    return render(request, 'main/index.html')


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    template_name = 'main/login.html'


@login_required
def profile(request):
    return render(request, 'main/profile.html')


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin,
                         UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Личные данные пользователя изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin,
                           PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_activated = True
        user.is_active = True
        user.save()
    return render(request, template)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

bboard/main/templates/layout/basic.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='slim' %}
    <title>{% block title %} Главная {% endblock %} - Design.pro </title>
</head>
<body>
<div class="container-fluid">
    <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3  bg-white border-bottom box-shadow">

        <h5 class="mr-md-auto p-2">Электронная доска объявлений</h5>

        {% if user.is_authenticated %}
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false">Профиль</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'main:profile' %}">Мои объявления</a>
                <a class="dropdown-item" href="{% url 'main:profile_change' %}">Изменить личные данные</a>
                <a class="dropdown-item" href="{% url 'main:password_change' %}">Изменить пароль</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'main:profile_delete' %}">Удалить</a>
            </div>
        </div>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'main:register' %}">Регистрация</a>
        <a class="p-2 text-dark" href="{% url 'main:login' %}">Вход</a>
        {% endif %}
        <a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
    </div>

    <div class="row">

        <nav class="col-md-auto nav flex-column">
            <a class="nav-link root" href="{% url 'main:index'  %}">Главная</a>
            <a class="nav-link" href="{% url 'main:new_orders'  %}">Новые заказы</a>
            <a class="nav-link" href="{% url 'main:doing_orders'  %}">Заказы в работе</a>
            <a class="nav-link" href="{% url 'main:done_orders'  %}">Выполненные заказы</a>
        </nav>

        <div class="container">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </div>

    </div>

    <footer class="mt-3 border-top">
        <small class="p-2"> &copy; Design.pro
            . 2022
        </small>
    </footer>
</div>

</body>
</html>

bboard/main/templates/main/bad_signature.html
{% extends "layout/basic.html" %}

{% block title %} Ошибка при активации {% endblock %}

{% block content %}
   <h2>Активация</h2>
   <p>Регистрация пользователя прошла неудачно.</p>
   <p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

bboard/main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Правка личных данных {% endblock %}

{% block content %}
   <h2>Правка личных данных пользователя {{ user.username }}</h2>
   <form method="post">
       {% csrf_token %}
       {% bootstrap_form form layout='horizontal' %}
       {% buttons submit='Сохранить' %} {% endbuttons %}
   </form>
{% endblock %}

bboard/main/templates/main/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Удаление пользователя {% endblock %}

{% block content %}
   <h2>Удаление пользователя {{ object.username }}</h2>
   <form method="post">
       {% csrf_token %}
       {% buttons submit='Удалить' %} {% endbuttons %}
   </form>
{% endblock %}

bboard/main/templates/main/doing_orders.html
{% extends "layout/basic.html" %}

{% block content %}
    <h1>Заказы в работе</h1>
{% endblock %}

bboard/main/templates/main/done_orders.html
{% extends "layout/basic.html" %}

{% block content %}
    <h1>Выполненные заказы</h1>
{% endblock %}

bboard/main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
   <h2>Последние 4 объявления</h2>
{% endblock %}

bboard/main/templates/main/login.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Вход {% endblock %}

{% block content %}
   <h2>Вход</h2>
   {% if user.is_authenticated %}
       <p>Вы уже выполнили вход.</p>
   {% else %}
       <form method="post">
           {% csrf_token %}
           {% bootstrap_form form layout='horizontal' %}
           <input type="hidden" name="next" value="{{ next }}">
           {% buttons submit='Войти' %} {% endbuttons %}
       </form>
   {% endif %}
{% endblock %}

bboard/main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %} Выход {% endblock %}

{% block content %}
   <h2>Выход</h2>
   <p>Вы успешно вышли с сайта.</p>
{% endblock %}

bboard/main/templates/main/new_orders.html
{% extends "layout/basic.html" %}

{% block content %}
    <h1>Новые заказы</h1>
{% endblock %}

bboard/main/templates/main/password_change.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Смена пароля {% endblock %}

{% block content %}
   <h2>Смена пароля пользователя {{ user.username }}</h2>
   <form method="post">
       {% csrf_token %}
       {% bootstrap_form form layout='horizontal' %}
       {% buttons submit='Сменить пароль' %} {% endbuttons %}
   </form>
{% endblock %}

bboard/main/templates/main/product.html
{% extends "layout/basic.html" %}

{% block content %}
    <h1>Страница объявления</h1>
{% endblock %}

bboard/main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% block title %} Регистрация завершена {% endblock %}

{% block content %}
   <h2>Регистрация</h2>
   <p>Регистрация пользователя завершена</p>
   <p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

bboard/main/templates/main/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Регистрация {% endblock %}

{% block content %}
   <h2>Регистрация нового пользователя</h2>
   <form method="post">
       {% csrf_token %}
       {% bootstrap_form form layout='horizontal' %}
       {% buttons submit='Зарегистрироваться' %} {% endbuttons %}
   </form>
{% endblock %}

bboard/main/templates/main/user_is_activated.html
{% extends "layout/basic.html" %}

{% block title %} Пользователь уже активирован {% endblock %}

{% block content %}
   <h2>Активация</h2>
   <p>Пользователь с таким именем уже был активирован ранее.</p>
   <p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}